### ISSUE TITLE
add CursorLine CursorColumn highlight

### ISSUE THREAD

**Issue by 257** [msharov/sc#2]
hello,
great stuff, this thing build with no fuss and works just fine on modern systems. i'm using kmscon so it would be nice if this thing could take advantage of new feature availabe to 256-color terms. for start, i would love to see line/column indicators, much like in vim. although i realise that there is no column highlight in vim but it's fitting for sc.

**Comment by doak** [comment]
"Major" cleanup (closing all three open issues)?

**Comment by msharov** [comment]
Since I have no plans of doing this anytime soon, you can consider this a "wontfix" situation. Lack of interest kills projects. I only cleaned up sc for a one-time use of editing Supreme Ruler 2020 config files, and have had no use for it since then. Well, ok, I also have a mc34064 parameter calc spreadsheet that I use once a year. Maybe I should just delete this repository altogether.

**Comment by msharov** [comment]
It is not unmaintained. It is merely unimproved. As the README suggests, please try sc-im if you want more features, but I do intend to keep it compiling properly.
