### ISSUE TITLE
u to Undo a command?

### ISSUE THREAD

**Issue by mascip** [msharov/sc#5]
Hi, I come from Vim where pressing u will undo the last action.

I didn't find this feature in sc, did I miss something?

Just to avoid possible confusion:
I have seen that I can use u while editing a cell entry, to undo the last editing action.
What I want instead, is to press u while in normal mode, to undo the last spreadsheet action (like deleting a column).

**Comment by btiffin** [comment]
@msharov; I've started to look into using sc from within COBOL console applications.  I'm leaning toward implementing Undo by leveraging the built in  Yank and Pull  features.   Adding 

    yankr(lookat(currow, curcol), lookat(currow, curcol));

just below the /* set mark '0' */ code in (for instance) the `=` entry operator (and `\`, `<`, `>`) for the strings,  allows for a simple  'pp'  to Pull cell from the 0 buffer to correct mistakes.   It's the equivalent of typing 'yy' to yank contents before any change.  Single level undo, using implicit yank.  I haven't dug into the more complicated Range functions yet, but the four simple changes so far have made `sc` edit sessions a much more comfortable experience.

Before spending too much more time on the experimental phase and getting to grips with row, column and box ranges, I'd like to ask what you think.  If it seems reasonable and not wrong minded, (it's pretty simple, so it might be a trap of wishful thinking), I'll prepare a patch set.  I'm working with the Fedora source RPM for sc-7.16, and for a quick look at what I mean, the above `yankr` call was put in, just below line 1140 of sc.c,  `case '='`, and it works the charm here, at least for the simple mistakes.

So, what do you think?  Is this a reasonable solution path, or wrong minded and missing out on important details?

Cheers

**Comment by msharov** [comment]
Doing a yank before every edit would overwrite a previous yank, which may have held something important. Yank, edit, copy, is not an uncommon edit sequence. In vim, I do it all the time. In any case, saving the data is not really the problem (the tables are readily available already), it is going through the code to identify all operations that can be undoed and figuring out a good place to put the saving hooks. Your solution does not do that, and so is not a good ida.

**Comment by btiffin** [comment]
Hrrmm, ;-)  it looked so promising.

How about, instead of hitting default '0', prep a named buffer, 'u' (or other documented letter) ??  That would add a "u to undo sequence.

For my use case, the default buffer has been working out fairly well.  Just adding what would amount to a stash away macro before write commands.  The first four changes (the one line yankr call), just to numeric and string entry, make for a less on-edge sc experience.

And yes, you're right, in the end. I was actually going to attack the issue by tracing what command keys trigger what effect and automating those steps in each of the other command key triggers.  Not so much reading deep code, more the documentation, and tracing the command (and edit) key code interpreters and planning what commands (if typed by hand) would rescue whatever command is at hand.

I'm taking your opinion to heart, but have to make one more grasp at the straw.

On, the technical side.  Instead of spending the many many hours it would take to fully understand the implications of each code path, is it safe to assume that

     yy
     command
     pp

is equivalent to

    command
    undo

from a high level, and just trigger that code, before executing any of the overwrite command code paths, from within the switch case key interpreters?  Let the plumbing be left to the core, and emulate a few implicit yanks with `yankr`  oneliners peppered throughout the keycode command interpreters??

I have no idea if that assumption of yy command pp is equivalent to command Undo,  (yy being yr, and pr, etc) is true or not.

Still wishful thinking, isn't it?    (I might not let go of the straw, without spending an hour or two more looking over the command code paths though).  :-)

Thanks, and cheers

**Comment by andmarti1424** [comment]
Hello Brian. May be you can try my app scim. Its in github as well and has the undo feature.

**Comment by msharov** [comment]
If you yank into a special buffer, without invalidating regular yanks, then I would have no problem with it.

A better way would be to work with andmarti1424, as he has offered, and port the undo feature from his scim project. Heck, why not just use scim in the first place? All I've done with sc was clean it up a little; I have not made any significant changes or added any features. That was enough for my uses, but now there's scim with its slew of new development. Perhaps it would make sense to switch.

andmarti1424: perhaps you should change the scim license to one of the standard ones to make it easier for people to understand how your project can be used. The way your custom license is currently written may possibly not meet the standard for open source licensing due to rather stringent requirements on sending back modifications.

**Comment by andmarti1424** [comment]
Just changed the license. Thanks for your suggestion.

2015-04-18 9:21 GMT-03:00 Mike Sharov <notifications@github.com>:

> If you yank into a special buffer, without invalidating regular yanks,
> then I would have no problem with it.
>
> A better way would be to work with andmarti1424, as he has offered, and
> port the undo feature from his scim project. Heck, why not just use scim in
> the first place? All I've done with sc was clean it up a little; I have not
> made any significant changes or added any features. That was enough for my
> uses, but now there's scim with its slew of new development. Perhaps it
> would make sense to switch.
>
> andmarti1424: perhaps you should change the scim license to one of the
> standard ones to make it easier for people to understand how your project
> can be used. The way your custom license is currently written may possibly
> not meet the standard for open source licensing due to rather stringent
> requirements on sending back modifications.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/msharov/sc/issues/5#issuecomment-94162290>.
>



-- 
Andrés Martinelli

**Comment by btiffin** [comment]
@msharov; I looked at scim, and yes it has a much nicer interactive interface, but my use case is driving sc from popen calls and the stdin stdout 'piping' macros that Chuck added.  With that in mind, I'd like to be able to pass sc files off to the less technically inclined, filling in speadsheets that become inputs to COBOL programs by simple stdin stdout sequencing.

@andmarti1424;  Nice changes by the way, but without commands like 'whereami' and command line args of -q etc, it becomes a lot harder to program scim from external tools, as is the plan here.

**Comment by andmarti1424** [comment]
May be we can add that, @btiffin. When I started scim I took sc source and cleaned & erased a lot of stuff I found to be messy.

**Comment by andmarti1424** [comment]
Hello btiffin. I am planning to add non interactive input and output to SCIM (the SC fork I am working on)..
I thought about these possibilities:
receive data from a script and output to file
receive data from a script and output to stdout
receive data throw piping and output to stdout
receive data throw piping and output to file
start interactive but with no curses interface (like bc)

What are for you the most important commands to get results ??
ex.:
GETNUM
GETSTRING
GETEXP
RECALC
GETROW?
GETCOLUMN?


Thanks!

Andrés

**Comment by btiffin** [comment]
Sorry, for the delay @andmarti1424.

I'm aiming to be able to include sc functionality inside COBOL programs, and literate project management documentation mixed with code, so am I allowed to say **all of the above** :-)

If I had to put a priority on wants and needs, piping to stdout, then interactive ala bc, then data from a script to stdout (via pipe read).  Output to file, I'd need/want last, but would still need of course.

For programmable functions, I'm really going to have to go with **all of the above**, as the list of priority needs would be very much on a case by case and sheet by sheet basis. 

I'll take another look at SCIM, (but you know you are eventually going to have to pick a new name if you ever want this to make into major repositories, right?)  (another smiley), and your code, really should be in the repos. Maybe *SCR*, sc set right?  scup, (which would be a fish, so meh, but it is reminiscent of smcup terminal capabilities) SCIMP is a messaging protocol already, umm?, but it would be sad for you to have to fight for the name once SCIM gains more fame.

They are some nice enhancements, making sc a lot more "boss" friendly, which is what I'd want/need if sc style spreadsheets where to be defensible from a GnuCOBOL application development point of view.

Keep up the good works, Andrés.
